const siteConfig = {
  theme: {
    active: "light",
    themes: {
      light: {
        pageBg: "#F6F1E8",
        pageBgWash: "#EFE7DB",
        surface: "#FFF9F2",
        surfaceAlt: "#F3ECE2",
        textPrimary: "#1F2430",
        textSecondary: "#5F6773",
        textMuted: "#7B8391",
        border: "rgba(31, 36, 48, 0.10)",
        borderStrong: "rgba(31, 36, 48, 0.16)",
        accentPrimary: "#C96A3D",
        accentPrimaryHover: "#B85C31",
        accentSoft: "#F3DFD3",
        accentCool: "#4F7C82",
        accentCoolSoft: "#DCE8E7",
        moss: "#7C8A63",
        clay: "#8B5E3C",
        cardShadow: "0 10px 30px rgba(60, 40, 20, 0.08)",
        elevatedShadow: "0 18px 45px rgba(60, 40, 20, 0.12)"
      },
      dark: {
        pageBg: "#0C1117",
        pageBgWash: "#111821",
        surface: "#151B23",
        surfaceAlt: "#1B2430",
        textPrimary: "#E8EDF5",
        textSecondary: "#B6C0CD",
        textMuted: "#8793A3",
        border: "rgba(255,255,255,0.10)",
        borderStrong: "rgba(255,255,255,0.16)",
        accentPrimary: "#D07A4B",
        accentPrimaryHover: "#C36C3E",
        accentSoft: "rgba(208, 122, 75, 0.18)",
        accentCool: "#6F9EA4",
        accentCoolSoft: "rgba(111, 158, 164, 0.20)",
        moss: "#91A070",
        clay: "#B68358",
        cardShadow: "0 10px 30px rgba(0, 0, 0, 0.22)",
        elevatedShadow: "0 18px 45px rgba(0, 0, 0, 0.32)"
      }
    }
  },
  links: {
    githubProfile: "https://github.com/brijbh"
  },
  assetGuidance: {
    previewImages: "1600x900 recommended, 1200x675 minimum",
    projectIcons: "SVG preferred, or 256x256 PNG",
    siteLogo: "512x512 or SVG preferred"
  },
  projects: [
    {
      id: "hoodi",
      name: "Hoodi",
      type: "Prompt ops / prompt workspace",
      tagline: "Prompt Ops workspace",
      description: "Test prompts, manage versions, compare results, and optimize with clarity.",
      status: "Prototype",
      tags: ["Prompt Ops", "Workspace", "Clarity"],
      accent: "#4F7C82",
      detailUrl: "hoodi.html",
      liveUrl: "https://hoodi.vercel.app",
      repoUrl: "https://github.com/brijbh/hoodi",
      iconPath: "assets/images/hoodi-icon.png",
      imagePath: "assets/images/hoodi-card-preview.jpg",
      imageMode: "screenshot",
      imageFit: "contain",
      imagePosition: "center top",
      previewAspect: "5 / 4",
      previewStyle: "workspace"
    },
    {
      id: "silkboard",
      name: "Silkboard",
      type: "ESOP earnings and tax calculator",
      legacyName: "Esopia",
      tagline: "ESOP earnings and tax calculator",
      description: "A practical calculator for thoughtful equity, earnings, and tax planning.",
      status: "Live",
      tags: ["Calculator", "ESOP", "Planning"],
      accent: "#7C8A63",
      detailUrl: "silkboard.html",
      liveUrl: "https://silkboard.vercel.app",
      repoUrl: "https://github.com/brijbh/silkboard",
      iconPath: "assets/images/silkboard-logo.svg",
      imagePath: "assets/images/silkboard.png",
      imageMode: "screenshot",
      imageFit: "contain",
      imagePosition: "center top",
      previewAspect: "5 / 4",
      previewStyle: "calculator"
    },
    {
      id: "ulsoor",
      name: "Ulsoor",
      type: "Kolam designs",
      tagline: "Kolam design explorer",
      description: "Explore generative kolam patterns inspired by traditional geometry and symmetry.",
      status: "Concept",
      tags: ["Kolam", "Geometry", "Canvas"],
      accent: "#C96A3D",
      detailUrl: "ulsoor.html",
      liveUrl: "https://ulsoor.vercel.app",
      repoUrl: "https://github.com/brijbh/ulsoor",
      iconPath: "assets/images/ulsoor-icon.png",
      imagePath: "assets/images/ulsoor.png",
      imageMode: "screenshot",
      imageFit: "contain",
      imagePosition: "center top",
      previewAspect: "5 / 4",
      previewStyle: "kolam"
    },
    {
      id: "domlur",
      name: "Domlur",
      type: "Pattern generation",
      tagline: "Pattern generator",
      description: "Create playful generative pattern compositions with simple visual controls.",
      status: "In Progress",
      tags: ["Patterns", "Generative", "Visual"],
      accent: "#8B5E3C",
      detailUrl: "domlur.html",
      liveUrl: "https://domlur.vercel.app",
      repoUrl: "https://github.com/brijbh/domlur",
      iconPath: "assets/images/domlur-icon.svg",
      imagePath: "assets/images/domlur.png",
      previewAspect: "5 / 4",
      previewStyle: "pattern"
    },
    {
      id: "whitefield",
      name: "Whitefield",
      type: "Color identification from photo",
      tagline: "Color ID from photo",
      description: "Extract and identify useful colors from any photo with clear visual analysis.",
      status: "Prototype",
      tags: ["Color", "Photo", "Utility"],
      accent: "#4F7C82",
      detailUrl: "whitefield.html",
      liveUrl: "https://whitefield.vercel.app",
      repoUrl: "https://github.com/brijbh/whitefield",
      iconPath: "assets/images/whitefield-icon.png",
      imagePath: "assets/images/whitefield.png",
      previewAspect: "5 / 4",
      previewStyle: "color"
    }
  ]
};
